include: package:sizzle_lints/lints.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
  exclude: 
    - "lib/src/core/localization/generated/**"

dart_code_metrics:
  extends:
    - package:sizzle_lints/dcm.yaml