name: sizzle_starter
description: Production-ready template for Flutter applications.
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.4 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  async: ^2.11.0
  meta: ^1.15.0
  intl: ^0.19.0

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.28.0

  # BLoC
  flutter_bloc: ^8.1.6

  # Storing data
  shared_preferences: ^2.3.2

  # Logging
  stack_trace: ^1.11.1
  sentry_flutter: ^8.9.0

  # Utils
  path: ^1.9.0
  path_provider: ^2.1.5
  package_info_plus: ^8.1.0
  circular_gradient_spinner: ^0.0.3

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Navigation
  auto_route: ^9.2.2

  clock: ^1.1.1

  # UI
  shadcn_ui: ^0.19.3
  google_fonts: ^6.2.1
  gap: ^3.0.1

dev_dependencies:
  # Testing
  mockito: ^5.4.4

  # Lints
  sizzle_lints: ^2.1.3

  # Utils
  flutter_gen_runner: ^5.8.0
  flutter_native_splash: ^2.4.2

  # Codegen
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  generate: true
  fonts:
    - family:  EcommerceIcons
      fonts:
       - asset: assets/fonts/EcommerceIcons.ttf
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/products/

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

flutter_launcher_icons:
  image_path: "assets/images/logo_app.png"
#  image_path_android: "assets/images/logo-app.png"
#  image_path_ios: "assets/images/logo-app.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#000000"