// ignore_for_file: non_constant_identifier_names, constant_identifier_names

/// Flutter icons EcommerceIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EcommerceIcons
///      fonts:
///       - asset: fonts/EcommerceIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

library;
import 'package:flutter/widgets.dart';

class EcommerceIcons {
  EcommerceIcons._();

  static const _kFontFam = 'EcommerceIcons';
  static const IconData address = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bag = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData box = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bxl_visa = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cancel_circle = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cancel = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData card = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cart = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cash = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData check_1 = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData chevron = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData circle = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData details = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData discount = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData headphones = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData heart_filled = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData image = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData location_filled = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData logos_apple_pay = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData logos_google_icon = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData mic = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData minus = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData phone_filled = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData question = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData return_icon = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData ri_mastercard_fill = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData truck_filled = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData warehouse_filled = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData warning_circle = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData web = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData whatsapp = IconData(0xe839, fontFamily: _kFontFam);
  static const IconData warning = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData eye_off = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData money_check_alt = IconData(0xf53d, fontFamily: _kFontFam);
}
